podcast_url: 
podcast_album_art: 
podcast_title: 
podcast_owner: 
podcast_email: 
podcast_category: 
podcast_subcategory_one: 
podcast_subcategory_two: 
podcast_explicit: 
podcast_author: 
podcast_description: 
podcast_summary: 
podcast_subtitle:
